-- local Tunnel = module('CLIMB', 'lib/Tunnel')
-- local Proxy = module('CLIMB', 'lib/Proxy')
-- CLIMB = Proxy.getInterface("CLIMB")

-- RegisterNetEvent('CLIMB:pdRadioPerms')
-- AddEventHandler('CLIMB:pdRadioPerms', function(status, b)
--     local source = source
--     local user_id = CLIMB.getUserId({source})
--     if CLIMB.hasPermission({user_id, 'police.armoury'}) then
--         TriggerClientEvent('CLIMB:pdRadioAnim', source, status, b)
--     end
-- end)
